### PR TITLE
Enabling Jasmine 2.4.1 with Jasmine Html Reporter

### PR DESCRIPTION
**Pull request by tarnowsc**
The Jasmine report in new version have slightly different css classes therefore the code is time-outing without finding proper elements.
Additionally I do believe the plugin should fail it it will not find explicit success message, otherwise (and it happen in my build) we can end up with failing test and successful build.

### CODE REVIEW

**Comment by tntim96** [comment]
The change looks good but will break some tests. I'll merge your changes locally, drop Jasmine 1 support and alter the tests accordingly then push it to github.

**Comment by tarnowsc** [comment]
Just realized that was building it with skip tests :(

I can update the test. Just give me some time

**Comment by tntim96** [comment]
OK. You can remove Jasmine 1 support and rename `Jasmine2...` files to `Jasmine...`.

**Comment by tarnowsc** [comment]
Ok, it seems that I've managed to remove old jasmine, leaving only jasmine 2, tests passed.

Please review the work done. Thanks in advance.

**Pull request merged**
